#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#

language: python

python:
  - 3.4
  - 3.5

services: postgresql

env:
  - DJANGO=1.10.2

before_install:
  - export DJANGO_SETTINGS_MODULE=recomovie.settings
  - export PYTHONPATH=$HOME/builds/sergiormb/recomovie
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install flake8

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py test

notifications:
  email:
    - sergiormb88@gmail.com
